### ISSUE TITLE
Did you try to use BLEURT on system level evaluation?

### ISSUE THREAD

**Issue by RoderickGu** [google-research/bleurt#10]
BLEURT is a great work and I kind of think it is also applicable on system-level evaluation. I wonder if you tried this? Thanks.

**Comment by tsellam** [comment]
Hi @RoderickGu thanks for your feedback!
We have no formal experiments, but in general we found that running BLEURT on multiple sentence pairs and averaging the scores works well. Let us know how it goes :)

**Comment by ratthachat** [comment]
Hi @RoderickGu , I am interested in your question, but I could not see a reference onsystem-level vs. sentence-level. Would you mind give some explanation?
