### ISSUE TITLE
file input from process substitution doesnt work

### ISSUE THREAD

**Issue by thammegowda** [google-research/bleurt#21]
this works:
```
 python -m bleurt.score  -candidate_file bleurt/test_data/candidates \
   -reference_file bleurt/test_data/references \
   -bleurt_checkpoint=bleurt/test_checkpoint
```
But this does not work (on my machine): 
```
python -m bleurt.score  -candidate_file <(head bleurt/test_data/candidates)
   -reference_file <(head bleurt/test_data/references) 
   -bleurt_checkpoint=bleurt/test_checkpoint
```
Why? 

NOTE: 
`<(head /path/to/file)` is meant to demostrate a simple usecase of [process subsititution](https://tldp.org/LDP/abs/html/process-sub.html)

In reality, someone like me would use 
`<(detokenize.sh <  /path/to/file)`
 or `<(cut -f2 /path/to/file.tsv)`
 and those should work with `tf.io.gfile.GFile`, right?

**Comment by tsellam** [comment]
Hi,
Thanks a lot for the detailed example.
Unfortunately I cannot accept pull requests at this point. 
I believe a simple workaround in this case to read the sentences from a file.
