### ISSUE TITLE
Can't use predict_fn with TF2

### ISSUE THREAD

**Issue by lhoestq** [google-research/bleurt#29]
Hi !

When I try to instantiate a PythonPredictor with a `predict_fn` function, I get this error:
```
    def __init__(self, predict_fn):
>     tf.logging.info("Creating Python-based predictor.")
E     AttributeError: module 'tensorflow' has no attribute 'logging'
```

I'm using TF2 so tensorflow.logging isn't available.

cc @tsellam I think this comes from the recent change to 0.0.2

**Comment by tsellam** [comment]
Hi! Good catch, thanks. I fixed the bug.

**Comment by lhoestq** [comment]
Thanks !
