### ISSUE TITLE
Code for Section 4 of the paper

### ISSUE THREAD

**Issue by vincent1rookie** [google-research/bleurt#32]
Hi,

I was wondering if you released the code for either generating synthetic sentence pairs or running pre-training tasks that you mentioned in the Section 4 of the BLEURT paper. Thank you!

**Comment by tsellam** [comment]
Hi Vincent,
Unfortunately we will not release this code, as it runs on a cluster.
We do provide the "warmed up" checkpoints though (see `README.md`).
