### ISSUE TITLE
Interpreting Bleurt scores

### ISSUE THREAD

**Issue by marcoavagnano98** [google-research/bleurt#41]
Hi,
sorry for the stupid question, maybe you have already answered to this.
You wrote: "In practice however, the answers tend to be very correlated with fluency ("Is the text fluent English?"), and we added synthetic noise in the training set which makes the distinction between adequacy and fluency somewhat fuzzy",
I'm a little bit confused by this.
Which are ultimately the aspects evaluated in the text by the metric in translation task?
Thanks and sorry for bad english ;)

**Comment by tsellam** [comment]
Hi, thanks for your feedback, this is actually a very good question. BLEURT depends on both fluency on adequacy, and unfortunately it's still unclear which one has the most influence.
Two great papers on the topic:
https://aclanthology.org/2021.emnlp-main.575.pdf
https://aclanthology.org/2021.emnlp-main.701.pdf
