### ISSUE TITLE
Optimising BLEURT for large dataset

### ISSUE THREAD

**Issue by awanteedeshpande** [google-research/bleurt#46]
Hi, great paper!
I am trying to use this implementation to compute BLEURT scores for > 60K English sentence pairs and even with the provided GPU optimisations, it takes days to calculate the scores. 
Is there any way to configure this to run in a shorter time?

**Comment by tsellam** [comment]
Hi, thanks for your feedback!
Please see the README for possible optimizations (e.g., same-length batching and distilled checkpoints).
