### ISSUE TITLE
UnrecognizedFlagError: Unknown command line flag 'f'

### ISSUE THREAD

**Issue by CinthiaS** [google-research/bleurt#7]
Hello! 

I'm trying to run the code below, following the instructions in the README, and I'm getting an error. Can you help me? Follow the code used and the output. The tensorflow version used is 2.2.0.

import os
!git clone https://github.com/google-research/bleurt.git
os.chdir('bleurt')
!pip install .
from bleurt import score
import tensorflow as tf

checkpoint = "bleurt/test_checkpoint"
references = ["This is a test."]
candidates = ["This is the test."]

scorer = score.BleurtScorer(checkpoint)
scores = scorer.score(references, candidates)
assert type(scores) == list and len(scores) == 1
print(scores)

---------------------------------------------------------------------------
UnrecognizedFlagError                     Traceback (most recent call last)
<ipython-input-9-ccc361b8056d> in <module>()
      9 
     10 scorer = score.BleurtScorer(checkpoint)
---> 11 scores = scorer.score(references, candidates)
     12 assert type(scores) == list and len(scores) == 1
     13 print(scores)

2 frames
/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py in __call__(self, argv, known_only)
    631       suggestions = _helpers.get_flag_suggestions(name, list(self))
    632       raise _exceptions.UnrecognizedFlagError(
--> 633           name, value, suggestions=suggestions)
    634 
    635     self.mark_as_parsed()

UnrecognizedFlagError: Unknown command line flag 'f'

**Comment by tsellam** [comment]
Hi!

Thanks for your message. It looks like you passed a flag "f" to your Python runtime, which Bleurt tries to pick up but fails to understand.

I see that you are mixing shell and Python commands--what kind of environment are you using? does the problem persist when you run it in "classic" command-line mode? (i.e., create a .py file and call the Python command)

**Comment by CinthiaS** [comment]
Hi!

Thanks for the reply! This error I am getting only when using Google Colab.

**Comment by machelreid** [comment]
@CinthiaS After you finish importing the dependencies, be sure to put this line:
```python
tf.compat.v1.flags.DEFINE_string('f','','')
```
It should help you avoid that error.
Let me know if it works!

**Comment by CinthiaS** [comment]
Thanks for the reply @machelreid! This solved my problem.

**Comment by tsellam** [comment]
Thanks for your advise @machelreid ! I am closing the Issue.
