### ISSUE TITLE
Python API test_checkpoint not found

### ISSUE THREAD

**Issue by shubhamagarwal92** [google-research/bleurt#8]
Hi,

Thank you for releasing the code. Interesting work! 

I am trying to use the [Python API](https://github.com/google-research/bleurt#python-api) in my code as:

```
from bleurt import score
checkpoint = "bleurt/test_checkpoint"
references = ["This is a test."]
candidates = ["This is the test."]
scorer = score.BleurtScorer(checkpoint)
```

however, the `bleurt/test_checkpoint` is not found. 
```
>>> scorer = score.BleurtScorer(checkpoint)
INFO:tensorflow:Reading checkpoint bleurt/test_checkpoint.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/metrics/lib/python3.7/site-packages/bleurt/score.py", line 133, in __init__
    config = checkpoint_lib.read_bleurt_config(checkpoint)
  File "/opt/conda/envs/metrics/lib/python3.7/site-packages/bleurt/checkpoint.py", line 78, in read_bleurt_config
    "Could not find BLEURT checkpoint {}".format(path)
AssertionError: Could not find BLEURT checkpoint bleurt/test_checkpoint
```

Is there a missing download link here? 

If I don't provide any checkpoint
```
scorer = score.BleurtScorer()
```
Expected: `If bleurt_checkpoint is not specified, BLEURT will default to the test checkpoint, based on BERT-Tiny`, however, I am getting the assertion error
```
>>> scorer = score.BleurtScorer()
INFO:tensorflow:No checkpoint specified, defaulting to BLEURT-tiny.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/metrics/lib/python3.7/site-packages/bleurt/score.py", line 130, in __init__
    checkpoint = _get_default_checkpoint()
  File "/opt/conda/envs/metrics/lib/python3.7/site-packages/bleurt/score.py", line 56, in _get_default_checkpoint
    "Default checkpoint not found! Are you sure the install is complete?"
AssertionError: Default checkpoint not found! Are you sure the install is complete?
```

Could you please suggest a way around. Thanks!

**Comment by machelreid** [comment]
Hi @shubhamagarwal92!

Usually when this problem arises, there is a problem with the path. Which directory are you running these commands from?

**Comment by shubhamagarwal92** [comment]
Hi @machelreid 

I am trying to use it as an API (Python package). 

Oh I see that I need to add a path related to the checkpoints. I guess I can't use the default checkpoint.

**Comment by machelreid** [comment]
I understand. For the default checkpoint you would have to specify the path to the directory which you installed BLEURT. In the case that you installed the package in your home directory, you would have to specify the following (absolute path):
```
checkpoint = "/home/user/bleurt/checkpoint"
scorer = score.BleurtScorer(checkpoint)
```
> I guess I can't use the default checkpoint.

The default checkpoint comes inside the BLEURT package without any extra installation. If you look inside your BLEURT installation directory, you should find a folder called `checkpoint` which contains the TF pretrained model.

Let me know if that makes sense. Thanks!

**Comment by tsellam** [comment]
Thanks a lot for your help Machel!

**Comment by tsellam** [comment]
`BleurtScorer()` should work with BLEURT-Tiny regardless of where the command is run, so there is a bug. We will look into it.
But in the meantime, @machelreid 's workaround should work.
